spring.application.name=user-service
server.port=8081

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.org.springframework.boot=INFO