'use client';

import { useEffect, useRef, useState } from 'react';
import { useAuth } from '@/features/auth/useAuth';
import { authService } from '@/services/auth.service';
import type { SavedTraveler } from '@/types/auth.types';
import { useActiveSessions, useSecurityEvents, useRevokeSessionMutation, useChangePasswordMutation } from '@/hooks/queries/useAccountQueries';

const currencies = [{ value: 'MAD', label: 'MAD — Dirham marocain' }, { value: 'EUR', label: 'EUR — Euro' }, { value: 'USD', label: 'USD — Dollar américain' }, { value: 'GBP', label: 'GBP — Livre sterling' }];
const languages = [{ value: 'fr', label: 'Français' }, { value: 'en', label: 'English' }];
type TravelerDraft = { firstName: string; lastName: string; dateOfBirth: string; travelerType: 'ADULT' | 'CHILD' | 'INFANT' };
const emptyTraveler: TravelerDraft = { firstName: '', lastName: '', dateOfBirth: '', travelerType: 'ADULT' };

export default function ProfilePage() {
  const { user, reloadProfile } = useAuth();
  const [profile, setProfile] = useState({ firstName: '', lastName: '', preferredCurrency: 'MAD', preferredLanguage: 'fr' });
  const [travelers, setTravelers] = useState<SavedTraveler[]>([]);
  const [travelerForm, setTravelerForm] = useState<TravelerDraft>(emptyTraveler);
  const [travelerFormOpen, setTravelerFormOpen] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [editingProfile, setEditingProfile] = useState(false);
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [loadingTravelers, setLoadingTravelers] = useState(true);
  const [saving, setSaving] = useState(false);
  const [photoBusy, setPhotoBusy] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const { data: sessions = [], isLoading: sessionsLoading } = useActiveSessions();
  const { data: securityEvents = [], isLoading: eventsLoading } = useSecurityEvents();
  const revokeSession = useRevokeSessionMutation();
  const changePassword = useChangePasswordMutation();
  const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });

  useEffect(() => { if (user) setProfile({ firstName: user.firstName, lastName: user.lastName, preferredCurrency: user.preferredCurrency || 'MAD', preferredLanguage: user.preferredLanguage || 'fr' }); }, [user]);
  useEffect(() => { void authService.getTravelers().then(setTravelers).catch(() => setFeedback({ type: 'error', text: 'Impossible de charger vos voyageurs.' })).finally(() => setLoadingTravelers(false)); }, []);
  const notify = (type: 'success' | 'error', text: string) => { setFeedback({ type, text }); window.setTimeout(() => setFeedback(null), 3500); };

  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await authService.updateProfile(profile); await reloadProfile(); setEditingProfile(false); notify('success', 'Modifications enregistrées.'); } catch (e: any) { notify('error', e.message || 'Impossible d’enregistrer les modifications.'); } finally { setSaving(false); } };
  const resend = async () => { try { await authService.resendVerification(); notify('success', 'E-mail de vérification envoyé.'); } catch (e: any) { notify('error', e.message || 'Impossible de renvoyer l’e-mail.'); } };
  const uploadPhoto = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { notify('error', 'Choisissez une image JPEG, PNG ou WEBP de 5 Mo maximum.'); return; } setPhotoBusy(true); try { await authService.uploadProfilePhoto(file); await reloadProfile(); notify('success', 'Photo de profil mise à jour.'); } catch (e: any) { notify('error', e.message || 'Impossible d’enregistrer la photo.'); } finally { setPhotoBusy(false); } };
  const removePhoto = async () => { setPhotoBusy(true); try { await authService.removeProfilePhoto(); await reloadProfile(); notify('success', 'Photo supprimée.'); } catch (e: any) { notify('error', e.message || 'Impossible de supprimer la photo.'); } finally { setPhotoBusy(false); } };
  const saveTraveler = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const saved = editing ? await authService.updateTraveler(editing, travelerForm) : await authService.createTraveler(travelerForm); setTravelers(current => editing ? current.map(item => item.reference === editing ? saved : item) : [...current, saved]); setEditing(null); setTravelerForm(emptyTraveler); setTravelerFormOpen(false); notify('success', editing ? 'Voyageur modifié.' : 'Voyageur ajouté.'); } catch (e: any) { notify('error', e.message || 'Impossible d’enregistrer ce voyageur.'); } finally { setSaving(false); } };
  const deleteTraveler = async (reference: string) => { if (!window.confirm('Supprimer ce voyageur enregistré ?')) return; try { await authService.deleteTraveler(reference); setTravelers(current => current.filter(item => item.reference !== reference)); notify('success', 'Voyageur supprimé.'); } catch (e: any) { notify('error', e.message || 'Impossible de supprimer ce voyageur.'); } };
  const changePasswordSubmit = async (event: React.FormEvent) => { event.preventDefault(); if (passwords.newPassword !== passwords.confirmPassword) return notify('error', 'Les nouveaux mots de passe ne correspondent pas.'); try { const result = await changePassword.mutateAsync({ currentPassword: passwords.currentPassword, newPassword: passwords.newPassword }); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }); notify('success', result.message || 'Mot de passe modifié.'); } catch (e: any) { notify('error', e.message || 'Impossible de modifier le mot de passe.'); } };

  return <main className="profile-page">
    <section className="profile-hero"><div><p className="eyebrow">ESPACE VOYAGEUR</p><h1>Mon profil</h1><p className="hero-copy">Préparez vos prochains départs et gardez vos préférences à portée de main.</p></div><div className="profile-hero-meta"><span className="hero-dot" />Compte personnel</div></section>
    {feedback && <div className={`feedback ${feedback.type}`} role="status">{feedback.text}</div>}
    <section className="identity-strip"><div className="photo-column"><div className="profile-photo">{user?.hasProfilePhoto ? <ProfilePhoto /> : <span>{user?.firstName?.charAt(0)?.toUpperCase() || 'U'}</span>}</div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={uploadPhoto} /><button className="text-button" onClick={() => fileRef.current?.click()} disabled={photoBusy}>{photoBusy ? 'Enregistrement…' : user?.hasProfilePhoto ? 'Remplacer la photo' : 'Ajouter une photo'}</button>{user?.hasProfilePhoto && <button className="subtle-button" onClick={removePhoto} disabled={photoBusy}>Supprimer</button>}</div><div className="identity-copy"><p className="eyebrow">VOTRE IDENTITÉ</p><h2>{user?.firstName} {user?.lastName}</h2><p>{user?.email}</p><div className="badges"><span className={user?.isEmailVerified ? 'badge verified' : 'badge pending'}>{user?.isEmailVerified ? '✓ E-mail vérifié' : 'E-mail non vérifié'}</span>{!user?.isEmailVerified && <button className="link-button" onClick={resend}>Renvoyer l’e-mail</button>}</div></div><div className="identity-aside"><span>Préférence d’affichage</span><strong>{user?.preferredCurrency || 'MAD'} · {user?.preferredLanguage === 'en' ? 'English' : 'Français'}</strong></div></section>
    <section className="profile-grid"><div className="content-column">
      <article className="profile-section"><div className="section-heading"><div><p className="eyebrow">INFORMATIONS PERSONNELLES</p><h2>Votre profil</h2></div>{!editingProfile && <button className="outline-button" onClick={() => setEditingProfile(true)}>Modifier</button>}</div>{editingProfile ? <form onSubmit={saveProfile} className="form-grid"><label>Prénom<input value={profile.firstName} onChange={e => setProfile({ ...profile, firstName: e.target.value })} required maxLength={100} /></label><label>Nom<input value={profile.lastName} onChange={e => setProfile({ ...profile, lastName: e.target.value })} required maxLength={100} /></label><label>Devise préférée<select value={profile.preferredCurrency} onChange={e => setProfile({ ...profile, preferredCurrency: e.target.value })}>{currencies.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Langue préférée<select value={profile.preferredLanguage} onChange={e => setProfile({ ...profile, preferredLanguage: e.target.value })}>{languages.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><div className="form-actions"><button className="primary-button" disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer'}</button><button type="button" className="subtle-button" onClick={() => setEditingProfile(false)}>Annuler</button></div></form> : <div className="details-grid"><div><span>Prénom</span><strong>{user?.firstName}</strong></div><div><span>Nom</span><strong>{user?.lastName}</strong></div><div><span>Devise</span><strong>{currencies.find(item => item.value === user?.preferredCurrency)?.label || 'MAD — Dirham marocain'}</strong></div><div><span>Langue</span><strong>{user?.preferredLanguage === 'en' ? 'English' : 'Français'}</strong></div></div>}</article>
      <article className="profile-section travelers-section"><div className="section-heading"><div><p className="eyebrow">POUR VOS PROCHAINS DÉPARTS</p><h2>Voyageurs enregistrés</h2><p className="section-copy">Ajoutez uniquement les informations utiles pour préremplir vos futurs voyages.</p></div><button className="primary-button" onClick={() => { setEditing(null); setTravelerForm(emptyTraveler); setTravelerFormOpen(true); }}>+ Ajouter</button></div>{loadingTravelers ? <div className="loading-line">Chargement…</div> : <div className="traveler-list">{travelers.length === 0 && <div className="empty-state"><strong>Aucun voyageur enregistré</strong><span>Créez un profil pour gagner du temps lors de votre prochaine recherche.</span></div>}{travelers.map(traveler => <div className="traveler-row" key={traveler.reference}><div className="traveler-avatar">{traveler.firstName.charAt(0).toUpperCase()}</div><div className="traveler-info"><strong>{traveler.firstName} {traveler.lastName}</strong><span>{traveler.travelerType === 'ADULT' ? 'Adulte' : traveler.travelerType === 'CHILD' ? 'Enfant' : 'Bébé'}{traveler.dateOfBirth ? ` · ${traveler.dateOfBirth}` : ''}</span></div><button className="row-action" onClick={() => { setEditing(traveler.reference); setTravelerForm({ firstName: traveler.firstName, lastName: traveler.lastName, dateOfBirth: traveler.dateOfBirth || '', travelerType: traveler.travelerType }); setTravelerFormOpen(true); }}>Modifier</button><button className="row-action danger" onClick={() => deleteTraveler(traveler.reference)}>Supprimer</button></div>)}</div>}{travelerFormOpen && <form onSubmit={saveTraveler} className="traveler-form"><h3>{editing ? 'Modifier le voyageur' : 'Nouveau voyageur'}</h3><div className="form-grid"><label>Prénom<input value={travelerForm.firstName} onChange={e => setTravelerForm({ ...travelerForm, firstName: e.target.value })} required maxLength={100} /></label><label>Nom<input value={travelerForm.lastName} onChange={e => setTravelerForm({ ...travelerForm, lastName: e.target.value })} required maxLength={100} /></label><label>Date de naissance (optionnel)<input type="date" value={travelerForm.dateOfBirth} onChange={e => setTravelerForm({ ...travelerForm, dateOfBirth: e.target.value })} /></label><label>Type<select value={travelerForm.travelerType} onChange={e => setTravelerForm({ ...travelerForm, travelerType: e.target.value as typeof travelerForm.travelerType })}><option value="ADULT">Adulte</option><option value="CHILD">Enfant</option><option value="INFANT">Bébé</option></select></label></div><div className="form-actions"><button className="primary-button" disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer'}</button><button type="button" className="subtle-button" onClick={() => { setEditing(null); setTravelerForm(emptyTraveler); setTravelerFormOpen(false); }}>Annuler</button></div></form>}</article>
    </div><aside className="side-column"><article className="profile-section security-card"><p className="eyebrow">SÉCURITÉ</p><h2>Mot de passe</h2><p className="section-copy">Un mot de passe unique protège votre espace voyageur.</p><form onSubmit={changePasswordSubmit}><label>Mot de passe actuel<input type="password" autoComplete="current-password" value={passwords.currentPassword} onChange={e => setPasswords({ ...passwords, currentPassword: e.target.value })} required /></label><label>Nouveau mot de passe<input type="password" autoComplete="new-password" minLength={8} value={passwords.newPassword} onChange={e => setPasswords({ ...passwords, newPassword: e.target.value })} required /></label><label>Confirmer le nouveau mot de passe<input type="password" autoComplete="new-password" minLength={8} value={passwords.confirmPassword} onChange={e => setPasswords({ ...passwords, confirmPassword: e.target.value })} required /></label><button className="primary-button" disabled={changePassword.isPending}>Mettre à jour</button></form></article><article className="profile-section sessions-card"><p className="eyebrow">ACCÈS AU COMPTE</p><h2>Sessions actives</h2>{sessionsLoading ? <div className="loading-line">Chargement…</div> : sessions.map(session => <div className="session-row" key={session.sessionId}><div><strong>{session.deviceLabel}</strong><span>{session.isCurrent ? 'Session actuelle' : new Date(session.lastUsedAt).toLocaleDateString()}</span></div>{!session.isCurrent && <button className="row-action danger" onClick={() => revokeSession.mutate(session.sessionId)}>Révoquer</button>}</div>)}</article></aside></section>
    <section className="security-events"><p className="eyebrow">JOURNAL DU COMPTE</p><h2>Activité de sécurité récente</h2>{eventsLoading ? <div className="loading-line">Chargement…</div> : securityEvents.length === 0 ? <p className="section-copy">Aucun événement récent.</p> : <div className="events-list">{securityEvents.slice(0, 5).map(event => <div key={event.id}><strong>{event.eventType}</strong><span>{new Date(event.createdAt).toLocaleString()}</span></div>)}</div>}</section>
  </main>;
}

function ProfilePhoto() { const { user } = useAuth(); const [url, setUrl] = useState<string | null>(null); useEffect(() => { let active = true; let objectUrl: string | null = null; setUrl(null); void authService.getProfilePhoto().then(blob => { if (active) { objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); } }).catch(() => {}); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [user?.updatedAt]); return url ? <img src={url} alt="" /> : <span>{user?.firstName?.charAt(0)?.toUpperCase() || 'U'}</span>; }
