spring.application.name=commentaire-service
server.port=8072

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# Spring Cloud Config Client
spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9091}
spring.cloud.config.enabled=true

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/commentaires_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.org.springframework.boot=INFO