package com.ahmed.travelservice.provider.error;

public enum ProviderErrorCode {
    PROVIDER_UNAVAILABLE,
    PROVIDER_NOT_CONFIGURED,
    PROVIDER_TIMEOUT,
    PROVIDER_RATE_LIMITED,
    PROVIDER_AUTHENTICATION_FAILED,
    PROVIDER_RESPONSE_INVALID,
    PROVIDER_QUOTA_EXHAUSTED,
    PROVIDER_REQUEST_INVALID,
    OFFER_NOT_FOUND,
    OFFER_EXPIRED,
    CAPABILITY_NOT_SUPPORTED,
    SCHEDULE_DATA_OUTDATED
}
