package com.ahmed.travelservice.provider.error;

public enum ProviderErrorCode {
    PROVIDER_UNAVAILABLE,
    PROVIDER_NOT_CONFIGURED,
    PROVIDER_TIMEOUT,
    PROVIDER_RATE_LIMITED,
    PROVIDER_AUTHENTICATION_FAILED,
    PROVIDER_RESPONSE_INVALID,
    OFFER_NOT_FOUND,
    OFFER_EXPIRED,
    CAPABILITY_NOT_SUPPORTED
}
