spring.application.name=ai-service
server.address=0.0.0.0
server.port=7777


spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9091}
spring.cloud.config.enabled=true
logging.level.org.springframework.cloud=DEBUG
logging.level.org.springframework.boot=DEBUG
# Activer et exposer les endpoints Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.diskspace.enabled=true
management.health.readinessstate.enabled=true

# Configurer la base de données pour le healthcheck
management.health.db.enabled=true
